{{- if and .Values.alertmanager.enabled .Values.alertmanager.persistentVolume.enabled -}}
{{- if not .Values.alertmanager.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.alertmanager.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.alertmanager.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.alertmanager.fullname" . }}

spec:
  {{- if .Values.alertmanager.persistentVolume.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.alertmanager.persistentVolume.storageClass | quote }}
  {{ else }}
  storageClassName: ""
  {{- end }}
  accessModes:
  
  resources:
    requests:
      storage: {{ .Values.alertmanager.persistentVolume.size | quote }}
  {{- if .Values.alertmanager.persistentVolume.useDynamicProvisioning  }}
  selector:
    matchLabels:
      assign-to: "alertmanager"
  {{- end }}
{{- end }}
{{- end }}
