nodeSelector.beta.kubernetes.io/arch:
   __metadata:
     name: "Node"
     label: "beta.kubernetes.io/arch"
     description: "Node Prefernce"
     type: "string"
     immutable: "false"
     required: true
     options:
     - label: "ppc64le"
       value: "ppc64le"
     - label: "amd64"
       value: "amd64"

