apiVersion: v1
appVersion: "1.0"
description: The Alertmanager handles alerts sent by client applications such as the
  Prometheus server. It takes care of deduplicating, grouping, and routing them to
  the correct receiver integrations such as email, PagerDuty, or OpsGenie. It also
  takes care of silencing and inhibition of alerts.
engine: gotpl
home: https://prometheus.io/docs/alerting/alertmanager/
icon: https://raw.githubusercontent.com/ppc64le/charts/master/logo/prometheus-alertmanager.jpg
keywords:
- alertmanager
- prometheus
- Limited
- ppc64le
- Tools
- ICP
maintainers:
- email: smohite@us.ibm.com
  name: IBM ISV Team
name: ibm-alertmanager
sources:
- https://github.com/prometheus/alertmanager
tillerVersion: '>=2.7.2'
version: 0.1.0
